stages:
  preprocess:
    cmd: |
      python src/preprocess/preprocess_data.py \
        data/raw/train.tsv \
        data/raw/validation.tsv \
        data/raw/test.tsv
    deps:
      - src/preprocess/preprocess_data.py
      - data/raw/train.tsv
      - data/raw/validation.tsv
      - data/raw/test.tsv
    outs:
      - data/processed/train_preprocessed.tsv
      - data/processed/validation_preprocessed.tsv
      - data/processed/test_preprocessed.tsv
  featurize:
    cmd: |
      python src/features/build_features.py \
        data/processed/train_preprocessed.tsv \
        data/processed/validation_preprocessed.tsv \
        data/processed/test_preprocessed.tsv
    deps:
      - src/features/build_features.py
      - data/processed/train_preprocessed.tsv
      - data/processed/validation_preprocessed.tsv
      - data/processed/test_preprocessed.tsv
    outs:
      - data/interim/train_featurized.tsv
      - data/interim/validation_featurized.tsv
      - data/interim/test_featurized.tsv
  train:
    cmd: python src/models/train_model.py data/interim/train_featurized.tsv
    deps:
      - src/models/train_model.py
      - data/interim/train_featurized.tsv
    outs:
      - models/model.pkl
  evaluation:
    cmd: python src/models/evaluate_model.py models/model.pkl
    deps:
      - src/models/evaluate_model.py
      - models/model.pkl
      - data/interim/validation_featurized.tsv
      - data/interim/test_featurized.tsv
    outs:
      - reports/figures/
      - reports/
