[tool.isort]
profile = "black"

[tool.black]
line-length = 119
include = '\.pyi?$'

[tool.bandit]
recursive = true
targets = "src/"
skips = ["B403", "B301"]

[tool.mypy]
ignore_missing_imports = true

[tool.pylint.format]
max-line-length = 119
disable = ["invalid-name"]
