apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-pv
spec:
  accessModes:
    - ReadWriteOnce # Minikube and its containers are in one node thus this choice
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/shared/dvc-cache
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
