apiVersion: v1
kind: Service
metadata:
  name: scraping-service
  labels:
    app: scraping-service
spec:
  type: ClusterIP
  selector:
    component: scraping-app
  ports:
    - port: 5000
      name: http
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraping-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: scraping-app
  template:
    metadata:
      labels:
        component: scraping-app
    spec:
      containers:
        - name: scraping-app
          image: ghcr.io/adam-tu/remla-project/scraping-service:latest
          imagePullPolicy: Always
          command: ["sh"]
          args: ["src/startup.sh"]
          ports:
            - containerPort: 5000
          env:
            - name: PROMETHEUS_MULTIPROC_DIR
              value: /tmp/prometheus/
            - name: APP_MODULE
              value: "scraping_service.app.scraper"
            - name: CONTROLLER_HOST
              value: "http://scraping-controller:5000"
            - name: SCRAPE_SAVE_DIR
              value: /data/shared/scrape/
          volumeMounts:
            - name: project-shared
              mountPath: /data/shared/
      volumes:
        - name: project-shared
          hostPath:
            path: /data/shared/

---
apiVersion: v1
kind: Service
metadata:
  name: scraping-controller
  labels:
    app: scraping-controller
spec:
  type: ClusterIP
  selector:
    component: scraping-controller
  ports:
    - port: 5000
      name: http
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraping-controller-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: scraping-controller
  template:
    metadata:
      labels:
        component: scraping-controller
    spec:
      containers:
        - name: scraping-controller
          image: ghcr.io/adam-tu/remla-project/scraping-controller:latest
          imagePullPolicy: Always
          command: ["sh"]
          args: ["src/startup.sh"]
          ports:
            - containerPort: 5000
          env:
            - name: PROMETHEUS_MULTIPROC_DIR
              value: "/tmp/prometheus/"
            - name: APP_MODULE
              value: "scraping_service.controller.controller"
            - name: SCRAPE_INCREMENT_SECONDS
              value: "600"
            - name: SCRAPE_START_TIMESTAMP
              value: "1641000000"
            - name: API_KEY_SECRET
              valueFrom:
                secretKeyRef:
                  name: api-keys
                  key: API_KEY